-- MySQL Script generated by MySQL Workbench
-- Fri Dec  8 09:48:17 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema oppgavedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema oppgavedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `oppgavedb` DEFAULT CHARACTER SET utf8 COLLATE utf8_danish_ci ;
USE `oppgavedb` ;

-- -----------------------------------------------------
-- Table `oppgavedb`.`brukere`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oppgavedb`.`brukere` ;

CREATE TABLE IF NOT EXISTS `oppgavedb`.`brukere` (
  `brukere_id` INT NOT NULL AUTO_INCREMENT,
  `brukernavn` VARCHAR(255) NOT NULL,
  `passord` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`brukere_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oppgavedb`.`lagrede_reiser`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oppgavedb`.`lagrede_reiser` ;

CREATE TABLE IF NOT EXISTS `oppgavedb`.`lagrede_reiser` (
  `lagrede_brukere_id` INT NOT NULL,
  `avgangstid` DATETIME NOT NULL,
  `ankomsttid` DATETIME NOT NULL,
  `legs_id` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_lagrede_reiser_brukere_idx` (`lagrede_brukere_id` ASC) VISIBLE,
  PRIMARY KEY (`legs_id`),
  CONSTRAINT `fk_lagrede_reiser_brukere`
    FOREIGN KEY (`lagrede_brukere_id`)
    REFERENCES `oppgavedb`.`brukere` (`brukere_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `oppgavedb`.`legs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `oppgavedb`.`legs` ;

CREATE TABLE IF NOT EXISTS `oppgavedb`.`legs` (
  `legs_legs_id` INT NOT NULL AUTO_INCREMENT,
  `linje` VARCHAR(255) NOT NULL,
  `destinasjon` VARCHAR(255) NOT NULL,
  `avgangstid` VARCHAR(255) NOT NULL,
  `ankomsttid` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`legs_legs_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
